name: Weather Data CICD

on:
  push:
    branches:
      - main

jobs:
  deploy-codebase:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # Required for Workload Identity Federation
      contents: read

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Authenticate to Google Cloud using Workload Identity Federation (keyless)
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/920571333004/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-ci@project-7d3bb007-d066-426a-b52.iam.gserviceaccount.com'

      # Setup Google Cloud SDK
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: project-7d3bb007-d066-426a-b52

      # Upload Spark Job to GCS
      - name: Upload Spark Job to GCS
        run: |
          gsutil cp spark_job/weather_data_processing.py gs://wether_forcasting_rawzone/script/

      # Upload Airflow DAG to Cloud Composer
      - name: Upload Airflow DAG to Composer
        run: |
          gcloud composer environments storage dags import \
            --environment  weather-forcasting-dag \
            --location us-central1 \
            --source wether-forcasting-airflow-dags
